/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pooproyecto;

import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import static pooproyecto.Registro1.usuarios;

/**
 *
 * @author cris1
 */
public class Registro1 extends javax.swing.JFrame {

    /**
     * Creates new form Registro
     */
    public Registro1() {
        initComponents();
        itemdoc.addItem("Cedula");
        itemdoc.addItem("TI");
        this.setLocationRelativeTo(null);
    }
   
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/LogoHuella.png"));
        return retValue;
    }
    
    public static ArrayList<Usuario> usuarios = new ArrayList();
     
   public static void crearArchivo(ArrayList lista) {
        Registro1 reg = new Registro1();
        FileWriter flwriter = null;
        try {
            flwriter = new FileWriter("C:\\archivos\\estudiantes.txt");
            BufferedWriter bfwriter = new BufferedWriter(flwriter);
            for (Usuario usu : reg.usuarios) {
                bfwriter.write(usu.getNombre() + "," + usu.getUsuario() + "," + usu.getContraseña() + "\n");
            }
            bfwriter.close();
            System.out.println("Archivo creado satisfactoriamente..");

        } catch (IOException e) {
            e.printStackTrace();
        } finally {
            if (flwriter != null) {
                try {
                    flwriter.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        doc = new javax.swing.JTextField();
        itemdoc = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tel = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fecha = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        con = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        BotonSalir = new javax.swing.JButton();
        mensaje = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(doc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 82, -1));

        itemdoc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        itemdoc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                itemdocItemStateChanged(evt);
            }
        });
        itemdoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemdocActionPerformed(evt);
            }
        });
        getContentPane().add(itemdoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 82, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Documento");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        guardar.setBackground(new java.awt.Color(153, 0, 153));
        guardar.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        guardar.setForeground(new java.awt.Color(255, 255, 255));
        guardar.setText("Guardar");
        guardar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        getContentPane().add(guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 269, 74, 31));

        jLabel3.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nro ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        tel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 82, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Telefono");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

        fecha.setText("DD/MM/AAAA");
        fecha.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, 82, -1));

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha de nacimiento (DD/MM/AAAA)");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        usu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(usu, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 82, -1));

        jLabel6.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        nom.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });
        getContentPane().add(nom, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 82, -1));

        con.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(con, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 82, 20));

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Contraseña");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, -1, -1));

        jButton1.setBackground(new java.awt.Color(153, 0, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic Light", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Atrás");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 60, 30));

        BotonSalir.setBackground(new java.awt.Color(153, 0, 153));
        BotonSalir.setFont(new java.awt.Font("Yu Gothic Light", 1, 11)); // NOI18N
        BotonSalir.setForeground(new java.awt.Color(255, 255, 255));
        BotonSalir.setText("Salir");
        BotonSalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(BotonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 60, 30));

        mensaje.setFont(new java.awt.Font("Yu Gothic Light", 1, 11)); // NOI18N
        mensaje.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 321, 15));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/2FondoPoo.jpg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemdocItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_itemdocItemStateChanged

    }//GEN-LAST:event_itemdocItemStateChanged

    private void itemdocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemdocActionPerformed

    }//GEN-LAST:event_itemdocActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
         if (!nom.getText().equals("") && !doc.getText().equals("") && !tel.getText().equals("") && !fecha.getText().equals("") && !usu.getText().equals("") && !con.getText().equals("")) {
            Usuario usuar = new Usuario();
            usuar.setNombre(nom.getText());
            String documento = (String) itemdoc.getSelectedItem();
            if (documento.equals("Cedula")) {
                usuar.setDocumento(TipoDocumento.cedula);
            } else {
                usuar.setDocumento(TipoDocumento.TI);
            }
            int id = Integer.parseInt(doc.getText());
            usuar.setNroIdentificacion(id);
            int tele = Integer.parseInt(tel.getText());
            usuar.setTelefono(tele);
            usuar.setFechaNacimento(fecha.getText());
            usuar.setUsuario(usu.getText());
            usuar.setContraseña(con.getText());
            boolean sw = false;

            for (Usuario us : usuarios) {
                if (us.getUsuario().equals(usuar.getUsuario())) {
                    sw = true;
                    mensaje.setText("NOMBRE DE USUARIO OCUPADO");
                    break;
                }
            }
            if (sw == false) {
                usuarios.add(usuar);
                mensaje.setText("USUARIO AGREGADO");
                iPets.usuarios.equals(usuarios);
                Inicio.usuarios.equals(usuarios);
                crearArchivo(usuarios);
                
            } else {
                usu.setText("");
            }

        } else {
            mensaje.setText("DEBE LLENAR TODOS LOS CAMPOS");
        }
         
    }//GEN-LAST:event_guardarActionPerformed

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        iPets ip = new iPets();
        ip.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_BotonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JLabel Fondo;
    private javax.swing.JTextField con;
    private javax.swing.JTextField doc;
    private javax.swing.JTextField fecha;
    private javax.swing.JButton guardar;
    private javax.swing.JComboBox<String> itemdoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel mensaje;
    private javax.swing.JTextField nom;
    private javax.swing.JTextField tel;
    private javax.swing.JTextField usu;
    // End of variables declaration//GEN-END:variables
}
